# Generated by Django 4.2 on 2024-01-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='expiration_date',
            field=models.DateTimeField(),
        ),
    ]
